### ISSUE TITLE
Error: Cannot find module './user'

### ISSUE THREAD

**Issue by javapcl** [marcosrivasr/Curso-de-NodeJS#2]
No entiendo que sucede ahí, no se porque encuentra el módulo user.

Error: Cannot find module './user'
Require stack:
- /home/runner/Login/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at /home/runner/Login/index.js:10:14
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by marcosrivasr** [comment]
@javapcl en qué archivo tienes ese problema?
